"""empty message

Revision ID: a810f69c7fc8
Revises: 
Create Date: 2022-06-29 19:50:49.546309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a810f69c7fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('contatoCliente', sa.String(length=11), nullable=True),
    sa.Column('enderecoCliente', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido', sa.String(length=100), nullable=True),
    sa.Column('entregador', sa.String(length=100), nullable=True),
    sa.Column('enderecoEntrega', sa.String(length=100), nullable=True),
    sa.Column('formaPagamento', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['enderecoEntrega'], ['cliente.enderecoCliente'], ),
    sa.ForeignKeyConstraint(['entregador'], ['entregador.nome'], ),
    sa.ForeignKeyConstraint(['pedido'], ['produto.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('entrega', sa.String(length=100), nullable=True),
    sa.Column('veiculo', sa.String(length=100), nullable=True),
    sa.Column('contatoEntregador', sa.String(length=11), nullable=True),
    sa.Column('pagamento', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['entrega'], ['produto.nome'], ),
    sa.ForeignKeyConstraint(['observacoes'], ['entrega.observacoes'], ),
    sa.ForeignKeyConstraint(['pagamento'], ['entrega.formaPagamento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('caracteristicaProduto', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['feedback'], ['suporte.feedback'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supermercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('enderecoSupermercado', sa.String(length=100), nullable=True),
    sa.Column('contatoSupermercado', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contatoSupermercado', sa.String(length=100), nullable=True),
    sa.Column('contatoCliente', sa.String(length=11), nullable=True),
    sa.Column('produto', sa.String(length=100), nullable=True),
    sa.Column('caracteristicas', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.String(length=150), nullable=True),
    sa.Column('contatoEntregador', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['caracteristicas'], ['produto.caracteristicaProduto'], ),
    sa.ForeignKeyConstraint(['contatoCliente'], ['cliente.enderecoCliente'], ),
    sa.ForeignKeyConstraint(['contatoEntregador'], ['entregador.contatoEntregador'], ),
    sa.ForeignKeyConstraint(['contatoSupermercado'], ['supermercado.contatoSupermercado'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suporte')
    op.drop_table('supermercado')
    op.drop_table('produto')
    op.drop_table('entregador')
    op.drop_table('entrega')
    op.drop_table('cliente')
    # ### end Alembic commands ###
